import urllib.request, json
with open('c:/Users/User/OneDrive/Documents/Commission/1. Basic Commission/3. Python Script/full_internal_basic_commission.py', 'r', encoding='utf-8') as f:
    lines = f.read().splitlines()

# find index of 'def _table4_rows'
idx = 0
for i, line in enumerate(lines):
    if line.startswith('def _table4_rows'):
        idx = i
        break

code = lines[:idx]

code.extend([
    'def _table4_rows(lines: list[InvoiceLine]) -> list[list[str]]:',
    '    \"\"\"',
    '    Referral Fee Table',
    '    \"\"\"',
    '    table_rows: list[list[str]] = []',
    '    for ln in lines:',
    '        if _is_valid_referral(ln.referral_name):',
    '            sales_price = ln.sales_price',
    '            rate = _referral_rate(ln.invoice_date)',
    '            fee = sales_price * rate',
    '            table_rows.append([',
    '                ln.referral_name.strip(),',
    '                ln.agent_name.strip(),',
    '                _fmt_money(sales_price),',
    '                _fmt_rate(rate),',
    '                _fmt_money(fee),',
    '            ])',
    '    table_rows.sort(key=lambda r: (r[0].lower(), r[1].lower()))',
    '    return table_rows',
    '',
    '',
    'def get_factory_rates(raw_rows: list[dict[str, Any]], cli_factory_rates: dict[str, Decimal] | None = None, default_profit_sharing: Decimal | None = None) -> dict[str, Decimal]:',
    '    cli_factory_rates = cli_factory_rates or {}',
    '    factory_invoices = [r for r in raw_rows if classify_property_type(r) == "Factory"]',
    '    factory_rates: dict[str, Decimal] = {}',
    '    if factory_invoices:',
    '        for r in factory_invoices:',
    '            inv_num = str(r.get("invoice_number") or "").strip()',
    '            cust_name = str(r.get("customer_name") or "(unknown)").strip()',
    '            total = _to_decimal(r.get("total_amount"))',
    '            epp = _to_decimal(r.get("epp_interest"))',
    '            sales_price = total - epp',
    '',
    '            if inv_num in cli_factory_rates:',
    '                factory_rates[inv_num] = cli_factory_rates[inv_num]',
    '            elif default_profit_sharing is not None:',
    '                factory_rates[inv_num] = default_profit_sharing',
    '            elif not sys.stdin.isatty():',
    '                factory_rates[inv_num] = Decimal("0")',
    '            else:',
    '                prompt_label = f"INV: {inv_num} | Customer: {cust_name} | Sales Price: {_fmt_money(sales_price)}"',
    '                while True:',
    '                    try:',
    '                        val = input(f"Insert Rate% for {prompt_label}: ").strip()',
    '                        if not val:',
    '                            rate_val = Decimal("0")',
    '                        else:',
    '                            rate_val = Decimal(val.replace("%", "").strip()) / Decimal("100")',
    '                        factory_rates[inv_num] = rate_val',
    '                        break',
    '                    except (KeyboardInterrupt, EOFError):',
    '                        print(f"\\nInterrupted. Defaulting profit sharing for {inv_num} to 0%.")',
    '                        factory_rates[inv_num] = Decimal("0")',
    '                        break',
    '                    except Exception as e:',
    '                        print(f"Invalid input: {e}. Please enter a numeric value (e.g. 5 or 5%).")',
    '    return factory_rates',
    '',
    '',
    'def main(argv: list[str]) -> int:',
    '    _load_dotenv()',
    '    parser = argparse.ArgumentParser(',
    '        description="Basic Commission report — Tables 1, 2, 3 and 4."',
    '    )',
    '    parser.add_argument("--year", type=int, default=2026)',
    '    parser.add_argument(',
    '        "--customer-contains",',
    '        action="append",',
    '        default=[],',
    '        help="Substring filter on customer name (repeat for OR).",',
    '    )',
    '    parser.add_argument(',
    '        "--profit-sharing",',
    '        type=float,',
    '        default=None,',
    '        help="Default profit sharing %% for Factory (e.g. 5.0 for 5%%)",',
    '    )',
    '    parser.add_argument(',
    '        "--factory-rates",',
    '        default=None,',
    '        help="JSON string or comma-separated key:value pairs mapping invoice_number to profit sharing %%",',
    '    )',
    '    parser.add_argument(',
    '        "--proxy-url",',
    '        default=_normalize_proxy_url(',
    '            _env(',
    '                "PG_PROXY_URL",',
    '                "https://pg-proxy-production.up.railway.app/api/sql",',
    '            )',
    '        ),',
    '    )',
    '    parser.add_argument(',
    '        "--db-name",',
    '        default=_env("PG_PROXY_DB") or _env("PG_DB_NAME", "prod_main"),',
    '    )',
    '    parser.add_argument(',
    '        "--pdf-output",',
    '        type=Path,',
    '        default=None,',
    '        help="PDF path",',
    '    )',
    '    parser.add_argument(',
    '        "--no-pdf",',
    '        action="store_true",',
    '        help="Do not write PDF file",',
    '    )',
    '    args = parser.parse_args(argv)',
    '',
    '    token = _env("PG_PROXY_TOKEN")',
    '    if not token:',
    '        print(',
    '            f"Missing PG_PROXY_TOKEN. Create or edit:\\n  {_SCRIPT_DIR / \'.env\'}",',
    '            file=sys.stderr,',
    '        )',
    '        return 2',
    '    if not args.proxy_url or not args.db_name:',
    '        print("Missing proxy URL or database name.", file=sys.stderr)',
    '        return 2',
    '',
    '    tokens: list[str] = []',
    '    for chunk in args.customer_contains:',
    '        for part in str(chunk).split(","):',
    '            part = part.strip()',
    '            if part:',
    '                tokens.append(part)',
    '    try:',
    '        customer_filter_sql = _customer_filter_sql(tokens)',
    '    except ValueError as e:',
    '        print(str(e), file=sys.stderr)',
    '        return 2',
    '',
    '    payload = _proxy_sql(',
    '        proxy_url=args.proxy_url,',
    '        db_name=args.db_name,',
    '        token=token,',
    '        sql=_invoices_sql(year=args.year, customer_filter_sql=customer_filter_sql),',
    '        params=[],',
    '    )',
    '    raw_rows = list(payload.get("rows") or [])',
    '    ',
    '    cli_factory_rates: dict[str, Decimal] = {}',
    '    if args.factory_rates:',
    '        raw_rates = args.factory_rates.strip()',
    '        if raw_rates.startswith("{"):',
    '            try:',
    '                parsed = json.loads(raw_rates)',
    '                for k, v in parsed.items():',
    '                    cli_factory_rates[str(k).strip()] = Decimal(str(v)) / Decimal("100")',
    '            except Exception as e:',
    '                print(f"Error parsing --factory-rates as JSON: {e}", file=sys.stderr)',
    '                return 1',
    '        else:',
    '            for part in raw_rates.split(","):',
    '                if not part.strip():',
    '                    continue',
    '                if ":" not in part:',
    '                    print(f"Error: --factory-rates format should be invoice_number:rate. Got: \'{part}\'", file=sys.stderr)',
    '                    return 1',
    '                k, _, v = part.partition(":")',
    '                try:',
    '                    cli_factory_rates[k.strip()] = Decimal(v.strip().replace("%", "")) / Decimal("100")',
    '                except Exception as e:',
    '                    print(f"Error parsing rate for invoice {k}: {e}", file=sys.stderr)',
    '                    return 1',
    '',
    '    default_profit_sharing = None',
    '    if args.profit_sharing is not None:',
    '        default_profit_sharing = Decimal(str(args.profit_sharing)) / Decimal("100")',
    '        ',
    '    factory_rates = get_factory_rates(raw_rows, cli_factory_rates, default_profit_sharing)',
    '    ',
    '    lines = _process_invoices(raw_rows, factory_rates)',
    '',
    '    user_count, table1 = _table1_rows(lines)',
    '    table2 = _table2_rows(lines)',
    '    table3 = _table3_rows(lines)',
    '    table4 = _table4_rows(lines)',
    '',
    '    print("=== Basic Commission Report ===")',
    '    print(f"Year (full_payment_date): {args.year}")',
    '    print("Filters: paid = TRUE, agent_type in (internal, full time)")',
    '    print(',
    '        "Customer filter: "',
    '        + (" OR ".join(repr(t) for t in tokens) if tokens else "(none)")',
    '    )',
    '    print(f"Total internal full-time agents: {user_count}")',
    '    print()',
    '    print("Rates: Executive m = 3.00%; Senior m = 3.25%; Factory = 2.00% + profit sharing")',
    '    print(',
    '        "Senior override: +0.25% of each report\'s accumulated basic commission (Executive tier only) "',
    '        "(Sunny: Jia Keat, Zulkarnain, Denise, Jia Xuan, Ah Zu; "',
    '        "Kent: Louis Ng, Anisah Najwa)"',
    '    )',
    '    print()',
    '',
    '    print("=== Table 1: Final Commission Payout Summary by agent ===")',
    '    print(_render_table(["Agent Name", "Total Sales", "Own Commission", "Senior Override Commission", "Total Commission Payout"], table1))',
    '    print()',
    '',
    '    print("=== Table 2: Accumulated Basic Commission by Customer (Residential and Shop Lot) ===")',
    '    print(',
    '        _render_table(',
    '            [',
    '                "Agent Name",',
    '                "Customer Name",',
    '                "Invoice Number",',
    '                "Package",',
    '                "Invoice Date",',
    '                "Full Payment Date",',
    '                "Total Amount",',
    '                "Epp",',
    '                "Sales Price",',
    '                "Rate %",',
    '                "Basic Commission",',
    '            ],',
    '            table2,',
    '        )',
    '    )',
    '    print()',
    '',
    '    print("=== Table 3: Accumulated Basic Commission by Customer (Factory) ===")',
    '    print(',
    '        _render_table(',
    '            [',
    '                "Agent Name",',
    '                "Customer Name",',
    '                "Invoice Number",',
    '                "Package",',
    '                "Invoice Date",',
    '                "Full Payment Date",',
    '                "Total Amount",',
    '                "Epp",',
    '                "Sales Price",',
    '                "Rate %",',
    '                "Profit Sharing",',
    '                "Basic Commission",',
    '            ],',
    '            table3,',
    '        )',
    '    )',
    '    print()',
    '',
    '    print("=== Table 4: Referral Fee ===")',
    '    print(',
    '        _render_table(',
    '            [',
    '                "Referral Name",',
    '                "Agent Name",',
    '                "Sales Price",',
    '                "Rate %",',
    '                "Referral Fee",',
    '            ],',
    '            table4,',
    '        )',
    '    )',
    '',
    '    # Save to CSV',
    '    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)',
    '    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")',
    '    ',
    '    csv_t1 = _OUTPUT_DIR / f"full_basic_commission_payout_summary_{args.year}_{stamp}.csv"',
    '    with open(csv_t1, "w", newline="", encoding="utf-8-sig") as f:',
    '        w = csv.writer(f)',
    '        w.writerow(["Agent Name", "Total Sales", "Own Commission", "Senior Override Commission", "Total Commission Payout"])',
    '        w.writerows(table1)',
    '        ',
    '    csv_t2 = _OUTPUT_DIR / f"full_basic_commission_residential_shoplot_{args.year}_{stamp}.csv"',
    '    with open(csv_t2, "w", newline="", encoding="utf-8-sig") as f:',
    '        w = csv.writer(f)',
    '        w.writerow([',
    '            "Agent Name", "Customer Name", "Invoice Number", "Package", "Invoice Date", "Full Payment Date",',
    '            "Total Amount", "Epp", "Sales Price", "Rate %", "Basic Commission"',
    '        ])',
    '        w.writerows(table2)',
    '        ',
    '    csv_t3 = _OUTPUT_DIR / f"full_basic_commission_factory_{args.year}_{stamp}.csv"',
    '    with open(csv_t3, "w", newline="", encoding="utf-8-sig") as f:',
    '        w = csv.writer(f)',
    '        w.writerow([',
    '            "Agent Name", "Customer Name", "Invoice Number", "Package", "Invoice Date", "Full Payment Date",',
    '            "Total Amount", "Epp", "Sales Price", "Rate %", "Profit Sharing", "Basic Commission"',
    '        ])',
    '        w.writerows(table3)',
    '',
    '    csv_t4 = _OUTPUT_DIR / f"full_basic_commission_referral_{args.year}_{stamp}.csv"',
    '    with open(csv_t4, "w", newline="", encoding="utf-8-sig") as f:',
    '        w = csv.writer(f)',
    '        w.writerow([',
    '            "Referral Name", "Agent Name", "Sales Price", "Rate %", "Referral Fee"',
    '        ])',
    '        w.writerows(table4)',
    '        ',
    '    print(f"CSV files saved to {_OUTPUT_DIR.resolve()}")',
    '',
    '    if not args.no_pdf:',
    '        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")',
    '        pdf_path = args.pdf_output or (',
    '            _OUTPUT_DIR / f"full_internal_basic_commission_{args.year}_{stamp}.pdf"',
    '        )',
    '        try:',
    '            _write_basic_pdf(',
    '                path=pdf_path,',
    '                year=args.year,',
    '                user_count=user_count,',
    '                customer_tokens=tokens,',
    '                table1=table1,',
    '                table2=table2,',
    '                table3=table3,',
    '                table4=table4,',
    '            )',
    '            print()',
    '            print(f"PDF saved: {pdf_path.resolve()}")',
    '        except ImportError as e:',
    '            print(f"\\nPDF not saved: {e}", file=sys.stderr)',
    '',
    '    return 0',
    '',
    '',
    'if __name__ == "__main__":',
    '    raise SystemExit(main(sys.argv[1:]))'
])

with open('c:/Users/User/OneDrive/Documents/Commission/1. Basic Commission/3. Python Script/full_internal_basic_commission.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(code) + '\n')
