"""Postgres storage for dashboard users, special cases, factory rates,
and audit log.

Replaces the old special_cases.json / factory_rates.json whole-file-overwrite
storage with proper tables, atomic writes, and per-change audit history.
Originally SQLite, then Supabase over psycopg2; now NUrul_DB, reached through
the pg-proxy HTTP endpoint (there is no postgres:// route to it) via pgproxy.py.
The tables live in that database's "dashboard" schema, keeping them clear of
the ERP's own `users` and `audit_log` in public.

Every call site below still reads as psycopg2 -- `with _connect() as conn`,
conn.execute(...).fetchall(), %s placeholders -- because pgproxy.Connection
implements that surface. See pgproxy.py for what the HTTP transport can and
cannot do; the one behavioural difference is that buffered writes are sent
when the block exits rather than statement by statement.
"""

from __future__ import annotations

import json
import os
import threading
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pgproxy

CURRENT_DIR = Path(__file__).resolve().parent
REPO_ROOT = CURRENT_DIR.parent
SPECIAL_CASES_JSON = CURRENT_DIR / "special_cases.json"
FACTORY_RATES_JSON = CURRENT_DIR / "factory_rates.json"

# Load DATABASE_URL regardless of whether the importing module (app.py) has
# already loaded its own .env — db.py must be able to connect on its own.
try:
    from dotenv import load_dotenv
    for _candidate in (CURRENT_DIR / ".env", REPO_ROOT / ".env"):
        if _candidate.is_file():
            load_dotenv(_candidate, override=False)
except ImportError:
    pass

# Kept only so a stale value in .env cannot silently send writes to the old
# Supabase project; nothing in this module connects with it any more.
DATABASE_URL = os.environ.get("DATABASE_URL")

_lock = threading.Lock()


@contextmanager
def _connect():
    """Open a proxy-backed transaction.

    Same contract as the psycopg2 version it replaces: commits on a clean
    exit, discards the pending writes on error. See pgproxy.Connection for how
    reads and writes are sequenced over HTTP.
    """
    with pgproxy.connect() as conn:
        yield conn


SPECIAL_CASE_FIELDS = [
    "agent", "customer", "pkg", "system", "nfp", "sales", "rate",
    "remarks", "profitSharingPct", "caseType", "specialCaseType", "feeWaiver",
    "adjustedSalesPrice",
    # Which commission row the case was raised from: "basic", "nfp", or "all"
    # (a whole new customer). Only that row is rebuilt — a case added from the
    # Net Floor Price row must not also restate the Basic Commission.
    "rowKind",
    # Gan Lai Soon's OGM override rate for this case, as a percent. His cut is
    # 0.75% of sales on most outsource invoices, but it is negotiated per agent,
    # so a case can carry its own. Blank/absent means the 0.75% default, which
    # is what every case saved before this field existed relies on.
    "ganOverridePct",
]

# Gan Lai Soon's OGM override when a case does not name its own rate. Defined
# here so app.py and the JS preview cannot drift to different defaults.
DEFAULT_GAN_OVERRIDE_PCT = 0.75


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def init_db() -> None:
    with _lock, _connect() as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL CHECK (role IN ('admin', 'staff')),
                is_active INTEGER NOT NULL DEFAULT 1,
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS special_cases (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                year TEXT NOT NULL,
                month TEXT NOT NULL,
                agent_type TEXT NOT NULL,
                data_json TEXT NOT NULL,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS factory_rates (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                year TEXT NOT NULL,
                month TEXT NOT NULL,
                agent_type TEXT NOT NULL,
                data_json TEXT NOT NULL,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS basic_rates (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                rate_type TEXT NOT NULL DEFAULT 'Basic Commission',
                agent_type TEXT NOT NULL,
                hierarchy TEXT NOT NULL,
                agent TEXT,
                rate_pct TEXT NOT NULL,
                effective_from TEXT NOT NULL,
                remarks TEXT,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS rule_settings (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                rule_key TEXT NOT NULL,
                label TEXT,
                value TEXT NOT NULL,
                effective_from TEXT NOT NULL,
                remarks TEXT,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            -- Unified rates + rules table (Data page). Supersedes basic_rates and
            -- rule_settings: one row can carry a rate AND a payout condition, which
            -- two separate tables could not express. The old tables are kept intact
            -- as a fallback/rollback path until this one is populated and verified.
            CREATE TABLE IF NOT EXISTS commission_rates (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                rate_type TEXT NOT NULL DEFAULT 'Basic Commission',
                agent_type TEXT,
                hierarchy TEXT,
                agent TEXT,
                label TEXT,
                rate_pct TEXT,
                override_rate_pct TEXT,
                override_from TEXT,
                profit_sharing_rate_pct TEXT,
                profit_sharing_mode TEXT,
                property_type TEXT,
                trigger_pct TEXT,
                invoice_date_from TEXT,
                rule_type TEXT,
                amount_rm TEXT,
                condition TEXT,
                effective_from TEXT NOT NULL,
                remarks TEXT,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            -- Who each agent is, what role they hold, and who they report to.
            -- Effective-dated like the rates, so a promotion or a branch move is
            -- a new row and recalculating an old month uses the hierarchy as it
            -- stood then. Replaces the hardcoded name-matching that used to live
            -- in the commission scripts.
            CREATE TABLE IF NOT EXISTS agent_roles (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                effective_from TEXT NOT NULL,
                agent TEXT NOT NULL,
                agent_type TEXT,
                hierarchy TEXT,
                reports_to TEXT,
                branch TEXT,
                remarks TEXT,
                start_date TEXT,
                nick_name TEXT,
                full_name TEXT,
                pg_bubble_id TEXT,
                hidden INTEGER,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS nfp_prices (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                month TEXT NOT NULL,
                panel_rating INTEGER NOT NULL,
                table_no INTEGER NOT NULL DEFAULT 1,
                panels INTEGER NOT NULL,
                final_price NUMERIC NOT NULL,
                final_with_tng NUMERIC,
                source_sheet TEXT,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            -- Monthly Contest rule set, one row per month. The contest is
            -- re-tuned every month (targets, handicaps, whether the activity
            -- bonus runs at all, which gift the Fast Start award gives), so the
            -- rules are stored per month rather than hardcoded in
            -- monthly_contest.py. Keeping the old months means an award queried
            -- in November can be checked against the rules as they stood then.
            -- Who is eligible to compete this month, and for which team. This
            -- is the Excel roster block: it decides who counts toward a team's
            -- revenue AND is the denominator for the "every member completed a
            -- deal" activity bonus, so a missing name changes award money.
            CREATE TABLE IF NOT EXISTS contest_roster (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                month TEXT NOT NULL,
                team TEXT NOT NULL,
                agent TEXT NOT NULL,
                sales_prices TEXT,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS contest_rules (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                month TEXT NOT NULL UNIQUE,
                full_rate_cap TEXT,
                above_cap_pct TEXT,
                activity_bonus_enabled INTEGER,
                activity_bonus_points TEXT,
                target_bonus_points TEXT,
                rank1_award TEXT,
                rank2_award TEXT,
                rank3_award TEXT,
                achievement_bonus TEXT,
                gb1_award TEXT,
                gb2_award TEXT,
                gb3_award TEXT,
                gb_min_cases TEXT,
                gb_min_sales TEXT,
                fast_start_gift TEXT,
                fast_start_slots TEXT,
                fast_start_unpaid TEXT,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            -- Per-team, per-month target and handicap. The six teams are fixed
            -- by the contest framework, so rows are always written as a set of
            -- six; only branch, captain, target and handicap vary.
            CREATE TABLE IF NOT EXISTS contest_team_month (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                month TEXT NOT NULL,
                team TEXT NOT NULL,
                branch TEXT,
                captain TEXT,
                original_target TEXT,
                handicap TEXT,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            -- ANP commission rules. Effective-dated so an old month recalculates
            -- against the tiers that applied then.
            CREATE TABLE IF NOT EXISTS anp_rules (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                effective_from TEXT NOT NULL UNIQUE,
                min_paid TEXT,
                excluded_payment_ids TEXT,
                invoice_overrides TEXT,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS anp_tiers (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                effective_from TEXT NOT NULL,
                from_amount TEXT,
                to_amount TEXT,
                commission_rm TEXT,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            -- EGA/ESA award rules, one set per year: the awards are annual.
            CREATE TABLE IF NOT EXISTS ega_rules (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                year TEXT NOT NULL,
                agent_type TEXT NOT NULL DEFAULT 'internal',
                ega_threshold TEXT,
                esa_threshold TEXT,
                factory_from TEXT,
                factory_first_block TEXT,
                factory_balance_rate TEXT,
                factory_min_panels TEXT,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS ega_month_thresholds (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                year TEXT NOT NULL,
                agent_type TEXT NOT NULL DEFAULT 'internal',
                month INTEGER NOT NULL,
                ep_threshold TEXT,
                label TEXT,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            -- Production bonus rules. The OUM/OSA/OGM role of each agent is NOT
            -- stored here: it comes from agent_roles, which is already the one
            -- place a promotion is recorded.
            CREATE TABLE IF NOT EXISTS production_bonus_rules (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                effective_from TEXT NOT NULL UNIQUE,
                min_paid TEXT,
                property_types TEXT,
                oum_team_target TEXT,
                oum_personal_target TEXT,
                oum_rate_pct TEXT,
                ogm_team_target TEXT,
                ogm_osa_rate_pct TEXT,
                ogm_oum_rate_pct TEXT,
                stage1_pct TEXT,
                stage2_pct TEXT,
                stage3_pct TEXT,
                created_by TEXT,
                created_at TEXT NOT NULL,
                updated_by TEXT,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS audit_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER,
                username TEXT NOT NULL,
                action TEXT NOT NULL CHECK (action IN ('create', 'update', 'delete')),
                entity_type TEXT NOT NULL,
                entity_summary TEXT,
                before_json TEXT,
                after_json TEXT,
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS login_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER,
                username TEXT NOT NULL,
                role TEXT,
                host TEXT,
                ip_address TEXT,
                user_agent TEXT,
                created_at TEXT NOT NULL
            );

            CREATE INDEX IF NOT EXISTS idx_basic_rates_lookup
                ON basic_rates (agent_type, hierarchy, effective_from);
            CREATE INDEX IF NOT EXISTS idx_nfp_prices_lookup
                ON nfp_prices (month, panel_rating, panels);
            CREATE INDEX IF NOT EXISTS idx_rule_settings_lookup
                ON rule_settings (rule_key, effective_from);
            CREATE INDEX IF NOT EXISTS idx_commission_rates_lookup
                ON commission_rates (rate_type, agent_type, hierarchy, effective_from);
            CREATE INDEX IF NOT EXISTS idx_agent_roles_lookup
                ON agent_roles (agent, effective_from);
            CREATE INDEX IF NOT EXISTS idx_special_cases_bucket
                ON special_cases (year, month, agent_type);
            CREATE INDEX IF NOT EXISTS idx_factory_rates_bucket
                ON factory_rates (year, month, agent_type);
            CREATE INDEX IF NOT EXISTS idx_contest_team_month_lookup
                ON contest_team_month (month, team);
            CREATE INDEX IF NOT EXISTS idx_audit_log_created_at
                ON audit_log (created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_login_log_created_at
                ON login_log (created_at DESC);

            -- Columns added after the tables above first shipped. Postgres's
            -- IF NOT EXISTS makes these safe to re-run every startup, unlike
            -- the PRAGMA table_info() dance SQLite needed.
            ALTER TABLE basic_rates ADD COLUMN IF NOT EXISTS rate_type TEXT NOT NULL DEFAULT 'Basic Commission';
            ALTER TABLE basic_rates ADD COLUMN IF NOT EXISTS agent TEXT;
            ALTER TABLE basic_rates ADD COLUMN IF NOT EXISTS condition TEXT;

            ALTER TABLE rule_settings ADD COLUMN IF NOT EXISTS rule_type TEXT;
            ALTER TABLE rule_settings ADD COLUMN IF NOT EXISTS trigger_pct TEXT;
            ALTER TABLE rule_settings ADD COLUMN IF NOT EXISTS agent_type TEXT;
            ALTER TABLE rule_settings ADD COLUMN IF NOT EXISTS hierarchy TEXT;
            ALTER TABLE rule_settings ADD COLUMN IF NOT EXISTS agent TEXT;
            ALTER TABLE rule_settings ADD COLUMN IF NOT EXISTS property_type TEXT;
            ALTER TABLE rule_settings ADD COLUMN IF NOT EXISTS invoice_date_from TEXT;

            ALTER TABLE commission_rates ADD COLUMN IF NOT EXISTS override_from TEXT;
            ALTER TABLE commission_rates ADD COLUMN IF NOT EXISTS profit_sharing_mode TEXT;

            ALTER TABLE nfp_prices ADD COLUMN IF NOT EXISTS package_price NUMERIC;
            ALTER TABLE nfp_prices ADD COLUMN IF NOT EXISTS tng_rebate NUMERIC;
            ALTER TABLE nfp_prices ADD COLUMN IF NOT EXISTS inverter_type TEXT DEFAULT 'string';
            ALTER TABLE nfp_prices ADD COLUMN IF NOT EXISTS power_system TEXT;
            ALTER TABLE nfp_prices ADD COLUMN IF NOT EXISTS columns_json TEXT;

            ALTER TABLE agent_roles ADD COLUMN IF NOT EXISTS start_date TEXT;
            ALTER TABLE agent_roles ADD COLUMN IF NOT EXISTS ic_no TEXT;
            ALTER TABLE agent_roles ADD COLUMN IF NOT EXISTS nick_name TEXT;
            ALTER TABLE agent_roles ADD COLUMN IF NOT EXISTS full_name TEXT;
            ALTER TABLE agent_roles ADD COLUMN IF NOT EXISTS pg_bubble_id TEXT;
            ALTER TABLE agent_roles ADD COLUMN IF NOT EXISTS hidden INTEGER;
            ALTER TABLE nfp_prices ALTER COLUMN final_price TYPE NUMERIC;
            ALTER TABLE nfp_prices ALTER COLUMN final_with_tng TYPE NUMERIC;
            ALTER TABLE nfp_prices ALTER COLUMN package_price TYPE NUMERIC;
            ALTER TABLE nfp_prices ALTER COLUMN tng_rebate TYPE NUMERIC;

            ALTER TABLE contest_roster ADD COLUMN IF NOT EXISTS sales_prices TEXT;
            -- EGA/ESA gained an agent-type dimension: the Outsource scheme uses
            -- higher EP thresholds than Internal. Existing rows are Internal.
            ALTER TABLE ega_rules ADD COLUMN IF NOT EXISTS agent_type TEXT NOT NULL DEFAULT 'internal';
            ALTER TABLE ega_month_thresholds ADD COLUMN IF NOT EXISTS agent_type TEXT NOT NULL DEFAULT 'internal';
            ALTER TABLE ega_rules DROP CONSTRAINT IF EXISTS ega_rules_year_key;
            CREATE UNIQUE INDEX IF NOT EXISTS idx_ega_rules_year_type ON ega_rules (year, agent_type);

            """
        )


def _load_json_list(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        return []
    return data if isinstance(data, list) else []


def migrate_from_json() -> None:
    """One-time import of legacy JSON rows into the database, if the tables are empty.

    The JSON files are left on disk untouched as a backup.
    """
    with _lock, _connect() as conn:
        sc_count = conn.execute("SELECT COUNT(*) FROM special_cases").fetchone()["count"]
        if sc_count == 0:
            for row in _load_json_list(SPECIAL_CASES_JSON):
                year = str(row.get("year", "2026"))
                month = str(row.get("month", "5"))
                agent_type = str(row.get("agent_type", "internal"))
                payload = {k: row.get(k) for k in SPECIAL_CASE_FIELDS}
                now = _now()
                conn.execute(
                    """INSERT INTO special_cases
                       (year, month, agent_type, data_json, created_by, created_at, updated_by, updated_at)
                       VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
                    (year, month, agent_type, json.dumps(payload), "(migrated)", now, "(migrated)", now),
                )

        fr_count = conn.execute("SELECT COUNT(*) FROM factory_rates").fetchone()["count"]
        if fr_count == 0:
            for row in _load_json_list(FACTORY_RATES_JSON):
                year = str(row.get("year", "2026"))
                month = str(row.get("month", "5"))
                agent_type = str(row.get("agent_type", "internal"))
                payload = {k: row.get(k) for k in row if k not in ("year", "month", "agent_type")}
                now = _now()
                conn.execute(
                    """INSERT INTO factory_rates
                       (year, month, agent_type, data_json, created_by, created_at, updated_by, updated_at)
                       VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
                    (year, month, agent_type, json.dumps(payload), "(migrated)", now, "(migrated)", now),
                )

        cr_count = conn.execute("SELECT COUNT(*) FROM commission_rates").fetchone()["count"]
        if cr_count == 0:
            now = _now()
            default_rates_and_rules = [
                {"rate_type": "Basic Commission", "agent_type": "Internal", "hierarchy": "Executive", "rate_pct": "3", "effective_from": "2026-01", "remarks": "Internal Executive Rate"},
                {"rate_type": "Basic Commission", "agent_type": "Internal", "hierarchy": "Senior", "rate_pct": "3.25", "override_rate_pct": "0.25", "override_from": "Executive", "effective_from": "2026-01", "remarks": "Internal Senior Rate & Override"},
                {"rate_type": "Basic Commission", "agent_type": "Outsource", "hierarchy": "OGM", "rate_pct": "5", "effective_from": "2026-01", "remarks": "Outsource OGM Rate"},
                {"rate_type": "Basic Commission", "agent_type": "Outsource", "hierarchy": "OUM", "rate_pct": "2.25", "override_rate_pct": "0.25", "override_from": "OSA/OSA1", "effective_from": "2026-01", "remarks": "Outsource OUM Rate & Override"},
                {"rate_type": "Basic Commission", "agent_type": "Outsource", "hierarchy": "OSA/OSA1", "rate_pct": "2", "effective_from": "2026-01", "remarks": "Outsource OSA Rate"},
                {"rate_type": "Basic Commission", "rule_type": "Payout", "trigger_pct": "100", "effective_from": "2026-01", "remarks": "Pre-Jul invoices: 100% payout when 100% paid"},
                {"rate_type": "Basic Commission", "rule_type": "Advance", "trigger_pct": "5", "invoice_date_from": "2026-07", "amount_rm": "300", "effective_from": "2026-07", "remarks": "Jul 2026+ invoices: RM300 advance payout when payment >= 5%"},
                {"rate_type": "Basic Commission", "rule_type": "Payout", "trigger_pct": "75", "invoice_date_from": "2026-07", "effective_from": "2026-07", "remarks": "Jul 2026+ invoices: balance payout when payment >= 75%"}
            ]
            for r in default_rates_and_rules:
                cols = ", ".join(COMMISSION_RATE_FIELDS)
                marks = ", ".join("%s" for _ in COMMISSION_RATE_FIELDS)
                vals = [r.get(k, "") for k in COMMISSION_RATE_FIELDS]
                conn.execute(
                    f"INSERT INTO commission_rates ({cols}, created_by, created_at, updated_by, updated_at) VALUES ({marks}, %s, %s, %s, %s)",
                    vals + ["(system)", now, "(system)", now]
                )


# ── Users ─────────────────────────────────────────────────────────────────────

def get_user_by_username(username: str) -> dict[str, Any] | None:
    with _connect() as conn:
        return conn.execute(
            "SELECT * FROM users WHERE username = %s AND is_active = 1", (username,)
        ).fetchone()


def get_user_by_id(user_id: int) -> dict[str, Any] | None:
    with _connect() as conn:
        return conn.execute("SELECT * FROM users WHERE id = %s", (user_id,)).fetchone()


def list_users() -> list[dict[str, Any]]:
    with _connect() as conn:
        return conn.execute(
            "SELECT id, username, role, is_active, created_at FROM users ORDER BY created_at ASC"
        ).fetchall()


def create_user(username: str, password_hash: str, role: str) -> int:
    with _lock, _connect() as conn:
        cur = conn.execute(
            "INSERT INTO users (username, password_hash, role, is_active, created_at) VALUES (%s, %s, %s, 1, %s) RETURNING id",
            (username, password_hash, role, _now()),
        )
        return cur.fetchone()["id"]


def update_user(user_id: int, *, username: str | None = None, password_hash: str | None = None,
                 role: str | None = None, is_active: bool | None = None) -> None:
    fields = []
    values: list[Any] = []
    if username is not None:
        fields.append("username = %s")
        values.append(username)
    if password_hash is not None:
        fields.append("password_hash = %s")
        values.append(password_hash)
    if role is not None:
        fields.append("role = %s")
        values.append(role)
    if is_active is not None:
        fields.append("is_active = %s")
        values.append(1 if is_active else 0)
    if not fields:
        return
    values.append(user_id)
    with _lock, _connect() as conn:
        conn.execute(f"UPDATE users SET {', '.join(fields)} WHERE id = %s", values)


def deactivate_user(user_id: int) -> None:
    update_user(user_id, is_active=False)


# ── Special cases ────────────────────────────────────────────────────────────

def get_special_cases(year: str, month: str, agent_type: str) -> list[dict[str, Any]]:
    with _connect() as conn:
        rows = conn.execute(
            """SELECT id, data_json FROM special_cases
               WHERE year = %s AND month = %s AND agent_type = %s""",
            (year, month, agent_type),
        ).fetchall()
    result = []
    for row in rows:
        item = json.loads(row["data_json"])
        item["id"] = row["id"]
        item["year"] = year
        item["month"] = month
        item["agent_type"] = agent_type
        result.append(item)
    return result


def save_special_cases(year: str, month: str, agent_type: str, new_cases: list[dict[str, Any]], username: str) -> None:
    """Replace the special cases for one (year, month, agent_type) bucket, logging an
    audit entry for every row removed, changed, or added."""
    now = _now()
    with _lock, _connect() as conn:
        existing_rows = conn.execute(
            """SELECT id, data_json FROM special_cases
               WHERE year = %s AND month = %s AND agent_type = %s""",
            (year, month, agent_type),
        ).fetchall()
        existing_payloads = [json.loads(r["data_json"]) for r in existing_rows]

        conn.execute(
            "DELETE FROM special_cases WHERE year = %s AND month = %s AND agent_type = %s",
            (year, month, agent_type),
        )

        new_payloads = [{k: c.get(k) for k in SPECIAL_CASE_FIELDS} for c in new_cases]
        for payload in new_payloads:
            conn.execute(
                """INSERT INTO special_cases
                   (year, month, agent_type, data_json, created_by, created_at, updated_by, updated_at)
                   VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
                (year, month, agent_type, json.dumps(payload), username, now, username, now),
            )

        if existing_payloads != new_payloads:
            summary = f"{agent_type} {month}/{year} special cases"
            conn.execute(
                """INSERT INTO audit_log
                   (user_id, username, action, entity_type, entity_summary, before_json, after_json, created_at)
                   VALUES (NULL, %s, 'update', 'special_case', %s, %s, %s, %s)""",
                (username, summary, json.dumps(existing_payloads), json.dumps(new_payloads), now),
            )


# ── Factory rates ─────────────────────────────────────────────────────────────

def get_factory_rates_rows(year: str, month: str, agent_type: str) -> list[dict[str, Any]]:
    with _connect() as conn:
        rows = conn.execute(
            """SELECT id, data_json FROM factory_rates
               WHERE year = %s AND month = %s AND agent_type = %s""",
            (year, month, agent_type),
        ).fetchall()
    result = []
    for row in rows:
        item = json.loads(row["data_json"])
        item["id"] = row["id"]
        item["year"] = year
        item["month"] = month
        item["agent_type"] = agent_type
        result.append(item)
    return result


def save_factory_rates(year: str, month: str, agent_type: str, new_rates: list[dict[str, Any]], username: str) -> None:
    now = _now()
    with _lock, _connect() as conn:
        existing_rows = conn.execute(
            """SELECT id, data_json FROM factory_rates
               WHERE year = %s AND month = %s AND agent_type = %s""",
            (year, month, agent_type),
        ).fetchall()
        existing_payloads = [json.loads(r["data_json"]) for r in existing_rows]

        conn.execute(
            "DELETE FROM factory_rates WHERE year = %s AND month = %s AND agent_type = %s",
            (year, month, agent_type),
        )

        new_payloads = [
            {k: r.get(k) for k in r if k not in ("year", "month", "agent_type", "id")}
            for r in new_rates
        ]
        for payload in new_payloads:
            conn.execute(
                """INSERT INTO factory_rates
                   (year, month, agent_type, data_json, created_by, created_at, updated_by, updated_at)
                   VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
                (year, month, agent_type, json.dumps(payload), username, now, username, now),
            )

        if existing_payloads != new_payloads:
            summary = f"{agent_type} {month}/{year} factory rates"
            conn.execute(
                """INSERT INTO audit_log
                   (user_id, username, action, entity_type, entity_summary, before_json, after_json, created_at)
                   VALUES (NULL, %s, 'update', 'factory_rate', %s, %s, %s, %s)""",
                (username, summary, json.dumps(existing_payloads), json.dumps(new_payloads), now),
            )


# ── Basic commission rates & rule settings (Data page) ───────────────────────

BASIC_RATE_FIELDS = ["rate_type", "agent_type", "hierarchy", "agent", "condition", "rate_pct", "effective_from", "remarks"]
NFP_PRICE_FIELDS = ["month", "panel_rating", "table_no", "panels", "final_price", "final_with_tng",
                    "package_price", "tng_rebate", "inverter_type", "power_system", "columns_json",
                    "source_sheet"]
RULE_SETTING_FIELDS = ["rule_key", "rule_type", "label", "value", "trigger_pct",
                       "agent_type", "hierarchy", "agent", "property_type",
                       "invoice_date_from", "effective_from", "remarks"]
# Unified table: every column a row may use, whether it is a plain rate, an
# override, a profit-sharing rate, an advance or a payout condition — or several
# of those at once (e.g. Safwan: a rate that only pays at 100% payment).
# property_type holds a comma-separated list ("Residential, Shop Lot") — a rate
# often applies to several property types at once.
COMMISSION_RATE_FIELDS = ["rate_type", "agent_type", "hierarchy", "agent", "label",
                          "rate_pct", "override_rate_pct", "override_from",
                          "profit_sharing_rate_pct", "profit_sharing_mode",
                          "property_type", "trigger_pct", "invoice_date_from",
                          "rule_type", "amount_rm", "condition",
                          "effective_from", "remarks"]


def _list_config_rows(table: str, order_by: str) -> list[dict[str, Any]]:
    with _connect() as conn:
        rows = conn.execute(f"SELECT * FROM {table} ORDER BY {order_by}").fetchall()
    return [dict(r) for r in rows]


def list_basic_rates() -> list[dict[str, Any]]:
    return _list_config_rows("basic_rates", "agent_type, hierarchy, effective_from")


def list_rule_settings() -> list[dict[str, Any]]:
    return _list_config_rows("rule_settings", "rule_key, effective_from")


AGENT_ROLE_FIELDS = ["effective_from", "agent", "agent_type", "hierarchy",
                     "reports_to", "branch", "remarks", "start_date", "ic_no",
                     "nick_name", "full_name", "pg_bubble_id", "hidden"]


def list_agent_roles() -> list[dict[str, Any]]:
    return _list_config_rows("agent_roles", "agent, effective_from")


def list_commission_rates() -> list[dict[str, Any]]:
    return _list_config_rows("commission_rates", "rate_type, agent_type, hierarchy, effective_from")


def _save_config_rows(table: str, fields: list[str], entity_type: str,
                      entity_summary: str, new_rows: list[dict[str, Any]], username: str) -> None:
    """Replace the whole table content, logging one audit entry with the diff."""
    now = _now()
    with _lock, _connect() as conn:
        existing_rows = conn.execute(f"SELECT * FROM {table} ORDER BY id").fetchall()
        existing_payloads = [{k: r[k] for k in fields} for r in existing_rows]

        conn.execute(f"DELETE FROM {table}")

        new_payloads = [{k: row.get(k) for k in fields} for row in new_rows]
        for payload in new_payloads:
            cols = ", ".join(fields)
            marks = ", ".join("%s" for _ in fields)
            conn.execute(
                f"""INSERT INTO {table} ({cols}, created_by, created_at, updated_by, updated_at)
                    VALUES ({marks}, %s, %s, %s, %s)""",
                [payload.get(k) for k in fields] + [username, now, username, now],
            )

        if existing_payloads != new_payloads:
            conn.execute(
                """INSERT INTO audit_log
                   (user_id, username, action, entity_type, entity_summary, before_json, after_json, created_at)
                   VALUES (NULL, %s, 'update', %s, %s, %s, %s, %s)""",
                (username, entity_type, entity_summary,
                 json.dumps(existing_payloads), json.dumps(new_payloads), now),
            )


def save_basic_rates(new_rows: list[dict[str, Any]], username: str) -> None:
    _save_config_rows("basic_rates", BASIC_RATE_FIELDS, "basic_rate",
                      "basic commission rates", new_rows, username)


def save_rule_settings(new_rows: list[dict[str, Any]], username: str) -> None:
    _save_config_rows("rule_settings", RULE_SETTING_FIELDS, "rule_setting",
                      "commission rule settings", new_rows, username)


def save_commission_rates(new_rows: list[dict[str, Any]], username: str) -> None:
    _save_config_rows("commission_rates", COMMISSION_RATE_FIELDS, "commission_rate",
                      "commission rates & rules", new_rows, username)


def save_agent_roles(new_rows: list[dict[str, Any]], username: str) -> None:
    _save_config_rows("agent_roles", AGENT_ROLE_FIELDS, "agent_role",
                      "agent role hierarchy", new_rows, username)


def list_nfp_prices() -> list[dict[str, Any]]:
    return _list_config_rows("nfp_prices", "month, panel_rating, table_no, panels")


def save_nfp_prices(new_rows: list[dict[str, Any]], username: str) -> None:
    _save_config_rows("nfp_prices", NFP_PRICE_FIELDS, "nfp_price",
                      "net floor price list", new_rows, username)


def replace_nfp_prices_for_months(months: list[str], new_rows: list[dict[str, Any]], username: str) -> int:
    """Replace the price rows of the given months only (an upload never touches
    other months). Returns the number of rows that were replaced."""
    now = _now()
    placeholders = ",".join("%s" for _ in months)
    with _lock, _connect() as conn:
        old_count = conn.execute(
            f"SELECT COUNT(*) FROM nfp_prices WHERE month IN ({placeholders})", months
        ).fetchone()["count"]
        conn.execute(f"DELETE FROM nfp_prices WHERE month IN ({placeholders})", months)
        for row in new_rows:
            cols = ", ".join(NFP_PRICE_FIELDS)
            marks = ", ".join("%s" for _ in NFP_PRICE_FIELDS)
            conn.execute(
                f"""INSERT INTO nfp_prices ({cols}, created_by, created_at, updated_by, updated_at)
                    VALUES ({marks}, %s, %s, %s, %s)""",
                [row.get(k) for k in NFP_PRICE_FIELDS] + [username, now, username, now],
            )
        conn.execute(
            """INSERT INTO audit_log
               (user_id, username, action, entity_type, entity_summary, before_json, after_json, created_at)
               VALUES (NULL, %s, 'update', 'nfp_price', %s, %s, %s, %s)""",
            (username, f"upload replaced months {', '.join(months)}",
             json.dumps({"replaced_rows": old_count}),
             json.dumps({"new_rows": len(new_rows), "months": months}), now),
        )
    return old_count


# ── Monthly Contest rules ─────────────────────────────────────────────────────

# Fixed by the contest framework — six teams, always in this order. Not editable
# from the Data page, so the stored rules can never drift out of sync with the
# framework by someone adding a seventh team.
CONTEST_TEAMS = ["England", "France", "Germany", "Brazil", "Spain", "Portugal"]

CONTEST_TEAM_FIELDS = ["team", "branch", "captain", "original_target", "handicap"]
CONTEST_ROSTER_FIELDS = ["team", "agent", "sales_prices"]

CONTEST_RULE_FIELDS = [
    "full_rate_cap", "above_cap_pct",
    "activity_bonus_enabled", "activity_bonus_points", "target_bonus_points",
    "rank1_award", "rank2_award", "rank3_award", "achievement_bonus",
    "gb1_award", "gb2_award", "gb3_award", "gb_min_cases", "gb_min_sales",
    "fast_start_gift", "fast_start_slots", "fast_start_unpaid",
]

# Used when a month has no saved rules yet. These reproduce what
# monthly_contest.py hardcodes today, so a month left untouched behaves exactly
# as it did before this page existed. fast_start_slots is deliberately blank —
# there is no sensible default for "how many jerseys", it has to be entered.
CONTEST_RULE_DEFAULTS = {
    "full_rate_cap": "40000",
    "above_cap_pct": "40",
    "activity_bonus_enabled": 1,
    "activity_bonus_points": "80000",
    "target_bonus_points": "50000",
    "rank1_award": "5000",
    "rank2_award": "3000",
    "rank3_award": "2000",
    "achievement_bonus": "2000",
    "gb1_award": "3000",
    "gb2_award": "2000",
    "gb3_award": "1000",
    "gb_min_cases": "3",
    "gb_min_sales": "150000",
    "fast_start_gift": "",
    "fast_start_slots": "",
    "fast_start_unpaid": "exclude",
}

CONTEST_TEAM_DEFAULTS = {
    "England": {"branch": "JB 1", "captain": "Vincent Tan", "original_target": "600000", "handicap": "0"},
    "France": {"branch": "JB 2", "captain": "Sunny", "original_target": "600000", "handicap": "0"},
    "Germany": {"branch": "JB 3", "captain": "Carol", "original_target": "600000", "handicap": "0"},
    "Brazil": {"branch": "Klang", "captain": "Jiawei", "original_target": "600000", "handicap": "0"},
    "Spain": {"branch": "Kluang 1", "captain": "Kent", "original_target": "450000", "handicap": "150000"},
    "Portugal": {"branch": "Kluang 2", "captain": "Wing On", "original_target": "450000", "handicap": "150000"},
}


def list_contest_rule_months() -> list[str]:
    """Months that have a saved rule set, newest first."""
    with _connect() as conn:
        rows = conn.execute("SELECT month FROM contest_rules ORDER BY month DESC").fetchall()
    return [r["month"] for r in rows]


def _contest_teams_from_rows(rows_by_team: dict[str, Any]) -> list[dict[str, Any]]:
    teams = []
    for name in CONTEST_TEAMS:
        row = rows_by_team.get(name)
        if row:
            teams.append({k: row[k] for k in CONTEST_TEAM_FIELDS})
        else:
            teams.append({"team": name, **CONTEST_TEAM_DEFAULTS[name]})
    return teams


def list_contest_rule_sets() -> list[dict[str, Any]]:
    """Every saved month with its rules and teams, newest first. The Data page
    landing table and its row popup both read from this one payload, so opening
    a month costs no extra round-trip."""
    with _connect() as conn:
        rule_rows = conn.execute("SELECT * FROM contest_rules ORDER BY month DESC").fetchall()
        team_rows = conn.execute("SELECT * FROM contest_team_month").fetchall()
        all_roster = conn.execute("SELECT * FROM contest_roster ORDER BY team, agent").fetchall()

    roster_by_month: dict[str, list[dict[str, Any]]] = {}
    for r in all_roster:
        roster_by_month.setdefault(r["month"], []).append({k: r[k] for k in CONTEST_ROSTER_FIELDS})

    by_month: dict[str, dict[str, Any]] = {}
    for row in team_rows:
        by_month.setdefault(row["month"], {})[row["team"]] = row

    sets = []
    for rule_row in rule_rows:
        rules = {k: rule_row[k] for k in CONTEST_RULE_FIELDS}
        rules["activity_bonus_enabled"] = 1 if rules.get("activity_bonus_enabled") else 0
        sets.append({
            "month": rule_row["month"],
            "saved": True,
            "rules": rules,
            "teams": _contest_teams_from_rows(by_month.get(rule_row["month"], {})),
            "roster": roster_by_month.get(rule_row["month"], []),
            "updated_by": rule_row["updated_by"],
            "updated_at": rule_row["updated_at"],
        })
    return sets


def get_contest_rules(month: str) -> dict[str, Any]:
    """The rule set for `month`. Falls back to the framework defaults when the
    month has not been set up yet, so the page always has something to show;
    `saved` tells the caller which of the two it got."""
    with _connect() as conn:
        rule_row = conn.execute(
            "SELECT * FROM contest_rules WHERE month = %s", (month,)
        ).fetchone()
        team_rows = conn.execute(
            "SELECT * FROM contest_team_month WHERE month = %s", (month,)
        ).fetchall()

    if rule_row:
        rules = {k: rule_row[k] for k in CONTEST_RULE_FIELDS}
    else:
        rules = dict(CONTEST_RULE_DEFAULTS)
    rules["activity_bonus_enabled"] = 1 if rules.get("activity_bonus_enabled") else 0

    teams = _contest_teams_from_rows({r["team"]: r for r in team_rows})
    with _connect() as conn:
        roster_rows = conn.execute(
            "SELECT * FROM contest_roster WHERE month = %s ORDER BY team, agent", (month,)
        ).fetchall()
    roster = [{k: r[k] for k in CONTEST_ROSTER_FIELDS} for r in roster_rows]
    return {"month": month, "saved": bool(rule_row), "rules": rules,
            "teams": teams, "roster": roster}


def save_contest_rules(month: str, rules: dict[str, Any], teams: list[dict[str, Any]],
                       username: str, roster: list[dict[str, Any]] | None = None) -> None:
    """Replace one month's rule set. Other months are never touched, so fixing
    August cannot alter what July's awards were calculated from."""
    now = _now()
    rule_payload = {k: rules.get(k) for k in CONTEST_RULE_FIELDS}
    rule_payload["activity_bonus_enabled"] = 1 if rules.get("activity_bonus_enabled") else 0

    by_team = {str(t.get("team")): t for t in teams}
    team_payloads = []
    for name in CONTEST_TEAMS:
        src = by_team.get(name, {})
        payload = {k: src.get(k) for k in CONTEST_TEAM_FIELDS}
        payload["team"] = name
        team_payloads.append(payload)

    with _lock, _connect() as conn:
        before_rule = conn.execute(
            "SELECT * FROM contest_rules WHERE month = %s", (month,)
        ).fetchone()
        before_teams = conn.execute(
            "SELECT * FROM contest_team_month WHERE month = %s ORDER BY team", (month,)
        ).fetchall()
        before_roster = conn.execute(
            "SELECT * FROM contest_roster WHERE month = %s ORDER BY team, agent", (month,)
        ).fetchall()
        before = {
            "rules": {k: before_rule[k] for k in CONTEST_RULE_FIELDS} if before_rule else None,
            "teams": [{k: r[k] for k in CONTEST_TEAM_FIELDS} for r in before_teams],
            "roster": [{k: r[k] for k in CONTEST_ROSTER_FIELDS} for r in before_roster],
        }

        conn.execute("DELETE FROM contest_rules WHERE month = %s", (month,))
        conn.execute("DELETE FROM contest_team_month WHERE month = %s", (month,))
        conn.execute("DELETE FROM contest_roster WHERE month = %s", (month,))

        cols = ", ".join(CONTEST_RULE_FIELDS)
        marks = ", ".join("%s" for _ in CONTEST_RULE_FIELDS)
        conn.execute(
            f"""INSERT INTO contest_rules (month, {cols}, created_by, created_at, updated_by, updated_at)
                VALUES (%s, {marks}, %s, %s, %s, %s)""",
            [month] + [rule_payload.get(k) for k in CONTEST_RULE_FIELDS]
            + [username, now, username, now],
        )

        t_cols = ", ".join(CONTEST_TEAM_FIELDS)
        t_marks = ", ".join("%s" for _ in CONTEST_TEAM_FIELDS)
        for payload in team_payloads:
            conn.execute(
                f"""INSERT INTO contest_team_month (month, {t_cols}, created_by, created_at, updated_by, updated_at)
                    VALUES (%s, {t_marks}, %s, %s, %s, %s)""",
                [month] + [payload.get(k) for k in CONTEST_TEAM_FIELDS]
                + [username, now, username, now],
            )

        roster_payloads = []
        for entry in (roster or []):
            team = str(entry.get("team") or "").strip()
            agent = str(entry.get("agent") or "").strip()
            if not team or not agent:
                continue          # a half-filled row is dropped, not stored blank
            # One agent can close several cases, so the row carries a list of
            # amounts. Anything unparseable is dropped rather than stored as a
            # case that would silently match the wrong invoice.
            raw_prices = entry.get("sales_prices")
            if isinstance(raw_prices, str):
                try:
                    raw_prices = json.loads(raw_prices or "[]")
                except ValueError:
                    raw_prices = []
            prices = []
            for value in (raw_prices or []):
                cleaned = str(value).replace(",", "").strip()
                if not cleaned:
                    continue
                try:
                    float(cleaned)
                except ValueError:
                    continue
                prices.append(cleaned)
            prices_json = json.dumps(prices)

            roster_payloads.append({"team": team, "agent": agent, "sales_prices": prices_json})
            conn.execute(
                """INSERT INTO contest_roster (month, team, agent, sales_prices, created_by, created_at, updated_by, updated_at)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
                (month, team, agent, prices_json, username, now, username, now),
            )

        after = {"rules": rule_payload, "teams": team_payloads, "roster": roster_payloads}
        if before != after:
            conn.execute(
                """INSERT INTO audit_log
                   (user_id, username, action, entity_type, entity_summary, before_json, after_json, created_at)
                   VALUES (NULL, %s, 'update', 'contest_rule', %s, %s, %s, %s)""",
                (username, f"Monthly Contest rules {month}",
                 json.dumps(before), json.dumps(after), now),
            )


# ── ANP / EGA-ESA / Production Bonus rules ────────────────────────────────────
#
# Each of these mirrors the values its calculation script hardcodes today, so a
# period with no saved rule set reproduces exactly what the script produced
# before the Data page existed.

ANP_RULE_FIELDS = ["min_paid", "excluded_payment_ids", "invoice_overrides"]
ANP_TIER_FIELDS = ["from_amount", "to_amount", "commission_rm"]

ANP_RULE_DEFAULTS = {
    "min_paid": "0.01",
    "excluded_payment_ids": "101334, 104412, 101333, 104413, 4899",
    "invoice_overrides": "",
}
ANP_TIER_DEFAULTS = [
    {"from_amount": "0", "to_amount": "59999.99", "commission_rm": "0"},
    {"from_amount": "60000", "to_amount": "179999.99", "commission_rm": "500"},
    {"from_amount": "180000", "to_amount": "359999.99", "commission_rm": "1000"},
    {"from_amount": "360000", "to_amount": "719999.99", "commission_rm": "1500"},
    {"from_amount": "720000", "to_amount": "", "commission_rm": "2000"},
]

EGA_RULE_FIELDS = ["ega_threshold", "esa_threshold", "factory_from",
                   "factory_first_block", "factory_balance_rate", "factory_min_panels"]
EGA_MONTH_FIELDS = ["month", "ep_threshold", "label"]

# Outsource runs the same award on higher EP thresholds, so the defaults split
# by agent type. Values match each script's hardcoded constants exactly.
EGA_RULE_DEFAULTS_BY_TYPE = {
    "internal": {"ega_threshold": "600000", "esa_threshold": "1300000"},
    "outsource": {"ega_threshold": "720000", "esa_threshold": "1560000"},
}

EGA_RULE_DEFAULTS = {
    "ega_threshold": "600000",
    "esa_threshold": "1300000",
    "factory_from": "2026-05",
    "factory_first_block": "40000",
    "factory_balance_rate": "40",
    "factory_min_panels": "36",
}
EGA_MONTH_DEFAULTS = [
    {"month": 2, "ep_threshold": "350000", "label": "EGA (Feb)"},
    {"month": 4, "ep_threshold": "450000", "label": "EGA (Apr)"},
    {"month": 5, "ep_threshold": "500000", "label": "EGA (May)"},
    {"month": 10, "ep_threshold": "1000000", "label": "ESA (Oct)"},
]

PB_RULE_FIELDS = ["min_paid", "property_types",
                  "oum_team_target", "oum_personal_target", "oum_rate_pct",
                  "ogm_team_target", "ogm_osa_rate_pct", "ogm_oum_rate_pct",
                  "stage1_pct", "stage2_pct", "stage3_pct"]

# OSA earns no production bonus, so it has no row here — only OUM and OGM do.
PB_RULE_DEFAULTS = {
    "min_paid": "0.01",
    "property_types": "Shop Lot, Residential",
    "oum_team_target": "2000000",
    "oum_personal_target": "300000",
    "oum_rate_pct": "0.5",
    "ogm_team_target": "8000000",
    "ogm_osa_rate_pct": "0.75",
    "ogm_oum_rate_pct": "0.25",
    "stage1_pct": "50",
    "stage2_pct": "30",
    "stage3_pct": "20",
}


def _get_period_rules(table, key_col, key, fields, defaults):
    with _connect() as conn:
        row = conn.execute(f"SELECT * FROM {table} WHERE {key_col} = %s", (key,)).fetchone()
    rules = {k: row[k] for k in fields} if row else dict(defaults)
    return bool(row), rules


def _save_period_rules(table, key_col, key, fields, rules, username,
                       child=None, entity="rule", summary=""):
    """Replace one period's rule set (and its child rows, if any). Other periods
    are never touched, so fixing one month cannot restate another."""
    now = _now()
    payload = {k: rules.get(k) for k in fields}
    with _lock, _connect() as conn:
        before_row = conn.execute(f"SELECT * FROM {table} WHERE {key_col} = %s", (key,)).fetchone()
        before = {"rules": {k: before_row[k] for k in fields} if before_row else None}

        conn.execute(f"DELETE FROM {table} WHERE {key_col} = %s", (key,))
        cols = ", ".join(fields)
        marks = ", ".join("%s" for _ in fields)
        conn.execute(
            f"""INSERT INTO {table} ({key_col}, {cols}, created_by, created_at, updated_by, updated_at)
                VALUES (%s, {marks}, %s, %s, %s, %s)""",
            [key] + [payload.get(k) for k in fields] + [username, now, username, now],
        )

        after = {"rules": payload}
        if child:
            child_table, child_fields, child_rows = child
            before_children = conn.execute(
                f"SELECT * FROM {child_table} WHERE {key_col} = %s ORDER BY id", (key,)
            ).fetchall()
            before["rows"] = [{k: r[k] for k in child_fields} for r in before_children]
            conn.execute(f"DELETE FROM {child_table} WHERE {key_col} = %s", (key,))
            c_cols = ", ".join(child_fields)
            c_marks = ", ".join("%s" for _ in child_fields)
            saved_children = []
            for r in child_rows:
                vals = {k: r.get(k) for k in child_fields}
                saved_children.append(vals)
                conn.execute(
                    f"""INSERT INTO {child_table} ({key_col}, {c_cols}, created_by, created_at, updated_by, updated_at)
                        VALUES (%s, {c_marks}, %s, %s, %s, %s)""",
                    [key] + [vals.get(k) for k in child_fields] + [username, now, username, now],
                )
            after["rows"] = saved_children

        if before != after:
            conn.execute(
                """INSERT INTO audit_log
                   (user_id, username, action, entity_type, entity_summary, before_json, after_json, created_at)
                   VALUES (NULL, %s, 'update', %s, %s, %s, %s, %s)""",
                (username, entity, f"{summary} {key}",
                 json.dumps(before), json.dumps(after), now),
            )


def get_anp_rules(effective_from: str) -> dict[str, Any]:
    saved, rules = _get_period_rules("anp_rules", "effective_from", effective_from,
                                     ANP_RULE_FIELDS, ANP_RULE_DEFAULTS)
    with _connect() as conn:
        rows = conn.execute(
            "SELECT * FROM anp_tiers WHERE effective_from = %s ORDER BY id", (effective_from,)
        ).fetchall()
    tiers = [{k: r[k] for k in ANP_TIER_FIELDS} for r in rows] or [dict(t) for t in ANP_TIER_DEFAULTS]
    return {"effective_from": effective_from, "saved": saved, "rules": rules, "tiers": tiers}


def save_anp_rules(effective_from, rules, tiers, username):
    _save_period_rules("anp_rules", "effective_from", effective_from, ANP_RULE_FIELDS,
                       rules, username,
                       child=("anp_tiers", ANP_TIER_FIELDS, tiers),
                       entity="anp_rule", summary="ANP commission rules")


def _ega_defaults(agent_type: str) -> dict[str, Any]:
    defaults = dict(EGA_RULE_DEFAULTS)
    defaults.update(EGA_RULE_DEFAULTS_BY_TYPE.get(agent_type, {}))
    return defaults


def get_ega_rules(year: str, agent_type: str = "internal") -> dict[str, Any]:
    agent_type = (agent_type or "internal").strip().lower()
    with _connect() as conn:
        row = conn.execute(
            "SELECT * FROM ega_rules WHERE year = %s AND agent_type = %s", (year, agent_type)
        ).fetchone()
        rows = conn.execute(
            "SELECT * FROM ega_month_thresholds WHERE year = %s AND agent_type = %s ORDER BY month",
            (year, agent_type),
        ).fetchall()
    rules = {k: row[k] for k in EGA_RULE_FIELDS} if row else _ega_defaults(agent_type)
    months = [{k: r[k] for k in EGA_MONTH_FIELDS} for r in rows] or [dict(m) for m in EGA_MONTH_DEFAULTS]
    return {"year": year, "agent_type": agent_type, "saved": bool(row),
            "rules": rules, "months": months}


def save_ega_rules(year, rules, months, username, agent_type: str = "internal"):
    """Replace one (year, agent type) rule set. Scoped by both keys so saving
    Outsource can never overwrite Internal's thresholds."""
    agent_type = (agent_type or "internal").strip().lower()
    now = _now()
    payload = {k: rules.get(k) for k in EGA_RULE_FIELDS}
    month_payloads = [{k: m.get(k) for k in EGA_MONTH_FIELDS} for m in (months or [])]
    with _lock, _connect() as conn:
        before_row = conn.execute(
            "SELECT * FROM ega_rules WHERE year = %s AND agent_type = %s", (year, agent_type)
        ).fetchone()
        before_months = conn.execute(
            "SELECT * FROM ega_month_thresholds WHERE year = %s AND agent_type = %s ORDER BY month",
            (year, agent_type),
        ).fetchall()
        before = {"rules": {k: before_row[k] for k in EGA_RULE_FIELDS} if before_row else None,
                  "months": [{k: r[k] for k in EGA_MONTH_FIELDS} for r in before_months]}

        conn.execute("DELETE FROM ega_rules WHERE year = %s AND agent_type = %s", (year, agent_type))
        conn.execute("DELETE FROM ega_month_thresholds WHERE year = %s AND agent_type = %s", (year, agent_type))

        cols = ", ".join(EGA_RULE_FIELDS)
        marks = ", ".join("%s" for _ in EGA_RULE_FIELDS)
        conn.execute(
            f"""INSERT INTO ega_rules (year, agent_type, {cols}, created_by, created_at, updated_by, updated_at)
                VALUES (%s, %s, {marks}, %s, %s, %s, %s)""",
            [year, agent_type] + [payload.get(k) for k in EGA_RULE_FIELDS] + [username, now, username, now],
        )
        m_cols = ", ".join(EGA_MONTH_FIELDS)
        m_marks = ", ".join("%s" for _ in EGA_MONTH_FIELDS)
        for m in month_payloads:
            conn.execute(
                f"""INSERT INTO ega_month_thresholds (year, agent_type, {m_cols}, created_by, created_at, updated_by, updated_at)
                    VALUES (%s, %s, {m_marks}, %s, %s, %s, %s)""",
                [year, agent_type] + [m.get(k) for k in EGA_MONTH_FIELDS] + [username, now, username, now],
            )

        after = {"rules": payload, "months": month_payloads}
        if before != after:
            conn.execute(
                """INSERT INTO audit_log
                   (user_id, username, action, entity_type, entity_summary, before_json, after_json, created_at)
                   VALUES (NULL, %s, 'update', 'ega_rule', %s, %s, %s, %s)""",
                (username, f"EGA/ESA award rules {year} ({agent_type})",
                 json.dumps(before), json.dumps(after), now),
            )


def get_production_bonus_rules(effective_from: str) -> dict[str, Any]:
    saved, rules = _get_period_rules("production_bonus_rules", "effective_from", effective_from,
                                     PB_RULE_FIELDS, PB_RULE_DEFAULTS)
    return {"effective_from": effective_from, "saved": saved, "rules": rules}


def save_production_bonus_rules(effective_from, rules, username):
    _save_period_rules("production_bonus_rules", "effective_from", effective_from,
                       PB_RULE_FIELDS, rules, username,
                       entity="production_bonus_rule", summary="Production bonus rules")


def list_rule_periods(table: str, key_col: str) -> list[str]:
    with _connect() as conn:
        rows = conn.execute(f"SELECT {key_col} FROM {table} ORDER BY {key_col} DESC").fetchall()
    return [r[key_col] for r in rows]


# ── Audit log ─────────────────────────────────────────────────────────────────

def insert_audit(username: str, action: str, entity_type: str, entity_summary: str,
                  before: Any = None, after: Any = None, user_id: int | None = None) -> None:
    with _lock, _connect() as conn:
        conn.execute(
            """INSERT INTO audit_log
               (user_id, username, action, entity_type, entity_summary, before_json, after_json, created_at)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
            (
                user_id, username, action, entity_type, entity_summary,
                json.dumps(before) if before is not None else None,
                json.dumps(after) if after is not None else None,
                _now(),
            ),
        )


def list_audit(entity_type: str | None = None, limit: int = 200, offset: int = 0) -> list[dict[str, Any]]:
    query = "SELECT * FROM audit_log"
    params: list[Any] = []
    if entity_type:
        query += " WHERE entity_type = %s"
        params.append(entity_type)
    query += " ORDER BY created_at DESC LIMIT %s OFFSET %s"
    params.extend([limit, offset])
    with _connect() as conn:
        rows = conn.execute(query, params).fetchall()
    return [dict(r) for r in rows]


# ── Login log ─────────────────────────────────────────────────────────────────

def insert_login(user_id: int | None, username: str, role: str | None, host: str | None,
                  ip_address: str | None, user_agent: str | None) -> None:
    with _lock, _connect() as conn:
        conn.execute(
            """INSERT INTO login_log
               (user_id, username, role, host, ip_address, user_agent, created_at)
               VALUES (%s, %s, %s, %s, %s, %s, %s)""",
            (user_id, username, role, host, ip_address, user_agent, _now()),
        )


def list_logins(limit: int = 200, offset: int = 0) -> list[dict[str, Any]]:
    with _connect() as conn:
        rows = conn.execute(
            "SELECT * FROM login_log ORDER BY created_at DESC LIMIT %s OFFSET %s",
            (limit, offset),
        ).fetchall()
    return [dict(r) for r in rows]
